### ISSUE TITLE
Solve bug on supervisord/nginx

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln-deploy#4]
We don't know why this bug is happening and it's really weird.
Sometimes we need to:
- Stop supervisord
- Restart nginx
- Start supervidord

So the web interface works correctly again (before it shows a '500 internal server error' page).

**Comment by flavioamieiro** [comment]
I've looked into it a bit (but not a lot, since the workaround is so easy). From what I remember it is about the PYTHON_EGG_CACHE being set to something like "//.python-eggs", which results in a permission error when trying to write to it.

Since restarting nginx and, after that, starting supervisor, my guess is that supervisor isn't getting the correct environment if nginx is not started, and I really don't understand that.

**Comment by flavioamieiro** [comment]
This started to happen every time I restarted the services, and the previous workaround stopped working. I solved the issue by defining the HOME variable myself before we call our python processes: 528accf013d4
